fix: typo fix and clean code 🚀

diff --git a/scripts/bin/vidl b/scripts/bin/vidl
--- a/scripts/bin/vidl
+++ b/scripts/bin/vidl
@@ -1,21 +1,24 @@
 #!/usr/bin/env bash
 
-gum_done() {
-    gum spin --spinner "globe" --title "Done! Press any key to close..." -- bash -c 'read -n 1 -s'
+set -eou pipefail
+
+msg() {
+    case "$1" in
+        "error") gum log --structured --level error "$2" | exit 1 ;;
+        "info") gum log --structured --level info "$2" ;;
+        "success") gum log --structured --level success "$2" ;;
+        "complete") gum spin --spinner "globe" --title "Done! Press any key to close..." -- bash -c 'read -n 1 -s' ;;
+    esac
 }
 
-gum_error() {
-    gum log --structured --level error "$1" | exit 1
-}
-
-Url=$(gum input --header.bold --header.foreground="#FCB8EF" --header="URL of video:" --placeholder="Enter URL..." || gum_error "Please enter a url.")
-VideoDownloadMode=$(gum choose --header="How many files to download:" --header.bold --header.foreground="#FCB8EF" "Single" "Batch" || gum_error "Please choose a video download mode.")
-DownloadDirectory=$(find "$HOME" -type d -not -path "$HOME/.*" -not -path "$HOME/.cache" | fzf --layout=reverse --height=50% --border || gum_error "Did not select a download directory.")
+Url=$(gum input --header.bold --header.foreground="#FCB8EF" --header="URL of video:" --placeholder="Enter URL..." || msg error "Please enter a url.")
+VideoDownloadMode=$(gum choose --header="How many files to download:" --header.bold --header.foreground="#FCB8EF" "Single" "Batch" || msg error "Please choose a video download mode.")
+DownloadDirectory=$(find "$HOME" -type d -not -path "$HOME/.*" -not -path "$HOME/.cache" | fzf --layout=reverse --height=50% --border || msg error "Did not select a download directory.")
 
 if [ -n "$Url" ]; then
     case "$VideoDownloadMode" in
         Single)
-            VideoQuality=$(gum choose --header="Choose video quality:" --header.bold --header.foreground="#FCB8EF" "Default" "720p" "1080p" || gum_error "Please choose video quality.")
+            VideoQuality=$(gum choose --header="Choose video quality:" --header.bold --header.foreground="#FCB8EF" "Default" "720p" "1080p" || msg error "Please choose video quality.")
             case "$VideoQuality" in
                 Default)
                     SeekOptions=$(gum choose --header="Download a portion of video?" --header.bold --header.foreground="#FCB8EF" "1. No Seek" "2. One point to Another" "3. One point to End of video")
@@ -26,7 +29,7 @@ if [ -n "$Url" ]; then
                         2*)
                             StartSeek=$(gum input --header.bold --header.foreground="#FCB8EF" --header="Enter seek start point:" --placeholder="HH:MM:SS or MM:SS or seconds")
                             EndSeek=$(gum input --header.bold --header.foreground="#FCB8EF" --header="Enter seek end point:" --placeholder="HH:MM:SS or MM:SS or seconds")
-                            yt-dlp --download-sections "*$StartSeek:$EndSeek" -o "$DownloadDirectory/%(title)s.%(ext)s" "$Url"
+                            yt-dlp --download-sections "*$StartSeek-$EndSeek" -o "$DownloadDirectory/%(title)s.%(ext)s" "$Url"
                             ;;
                         3*)
                             StartSeek=$(gum input --header.bold --header.foreground="#FCB8EF" --header="Enter seek start point:" --placeholder="HH:MM:SS or MM:SS or seconds")
@@ -73,6 +76,6 @@ if [ -n "$Url" ]; then
         Batch) ;;
     esac
 else
-    gum_error "Enter a URL..."
-    gum_done
+    msg error "Enter a URL..."
+    msg complete
 fi
